services:
  finances:
    build:
      context: https://github.com/jgoedde/Finances.git#v1.13.1
      dockerfile: Dockerfile
    image: finances-client:latest
    ports:
      - "8787:80"
    restart: unless-stopped
