services:
  finances:
    build:
      context: https://github.com/jgoedde/Finances.git#${FINANCES_VERSION}
      dockerfile: Dockerfile
    image: finances-client:${FINANCES_VERSION}
    ports:
      - "8787:80"
    restart: unless-stopped
