title: Homelab
theme: dark
color: slate
statusStyle: dot

layout:
  Photos:
    style: row
    columns: 4
  Music:
    style: row
    columns: 4
  Bookmarks:
    style: row
    columns: 4
  Documents:
    style: row
    columns: 4
  Sync:
    style: row
    columns: 4
  Utilities:
    style: row
    columns: 4
