---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /
    uptime: true
- datetime:
    text_size: xl
    # 4 januari 2023 om 13:51:25 PST
    locale: de
    format:
      dateStyle: long
      timeStyle: long

