services:
  app:
    image: jc21/nginx-proxy-manager:2.15.1
    restart: unless-stopped
    environment:
      TZ: "Europe/Berlin"
    ports:
      - '80:80'
      - '127.0.0.1:81:81' # admin UI
      - '443:443'
      - '8787:443' # finances client
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - npm-proxy

networks:
  npm-proxy:
    external: true
